
export enum AppView {
  HOME = 'HOME',
  AI_GENERATOR = 'AI_GENERATOR',
  AI_CHAT = 'AI_CHAT',
  AI_MARKDOWN = 'AI_MARKDOWN',
  AI_RESUME_SCORER = 'AI_RESUME_SCORER',
  AI_TRANSLATOR = 'AI_TRANSLATOR',
  IMAGE_TO_PDF = 'IMAGE_TO_PDF',
  MERGE_PDF = 'MERGE_PDF',
  SPLIT_PDF = 'SPLIT_PDF',
  REMOVE_PAGES = 'REMOVE_PAGES',
  EXTRACT_PAGES = 'EXTRACT_PAGES',
  ORGANIZE_PDF = 'ORGANIZE_PDF',
  ROTATE_PDF = 'ROTATE_PDF',
  PROTECT_PDF = 'PROTECT_PDF',
  UNLOCK_PDF = 'UNLOCK_PDF',
  WATERMARK_PDF = 'WATERMARK_PDF',
  NUMBER_PDF = 'NUMBER_PDF',
  BATES_NUMBERING = 'BATES_NUMBERING',
  COMPRESS_PDF = 'COMPRESS_PDF',
  OCR_PDF = 'OCR_PDF',
  PDF_TO_WORD = 'PDF_TO_WORD',
  PDF_TO_EXCEL = 'PDF_TO_EXCEL',
  PDF_TO_POWERPOINT = 'PDF_TO_POWERPOINT',
  WORD_TO_PDF = 'WORD_TO_PDF',
  EXCEL_TO_PDF = 'EXCEL_TO_PDF',
  POWERPOINT_TO_PDF = 'POWERPOINT_TO_PDF',
  HTML_TO_PDF = 'HTML_TO_PDF',
  PDF_TO_JPG = 'PDF_TO_JPG',
  PDF_TO_PDFA = 'PDF_TO_PDFA',
  EDIT_PDF = 'EDIT_PDF',
  CROP_PDF = 'CROP_PDF',
  SIGN_PDF = 'SIGN_PDF',
  REPAIR_PDF = 'REPAIR_PDF',
  COMPARE_PDF = 'COMPARE_PDF',
  REDACT_PDF = 'REDACT_PDF',
  SCAN_TO_PDF = 'SCAN_TO_PDF',
  GRAYSCALE_PDF = 'GRAYSCALE_PDF',
  SANITIZE_PDF = 'SANITIZE_PDF',
  METADATA_EDITOR = 'METADATA_EDITOR',
  // New Data & Dev Tools
  JSON_TO_PDF = 'JSON_TO_PDF',
  XML_TO_PDF = 'XML_TO_PDF',
  CSV_TO_PDF = 'CSV_TO_PDF',
  LOG_TO_PDF = 'LOG_TO_PDF',
  SQL_TO_PDF = 'SQL_TO_PDF',
  // New Image Converters
  PNG_TO_PDF = 'PNG_TO_PDF',
  TIFF_TO_PDF = 'TIFF_TO_PDF',
  BMP_TO_PDF = 'BMP_TO_PDF',
  GIF_TO_PDF = 'GIF_TO_PDF',
  SVG_TO_PDF = 'SVG_TO_PDF',
  // New Document Converters
  ODT_TO_PDF = 'ODT_TO_PDF',
  ODS_TO_PDF = 'ODS_TO_PDF',
  ODP_TO_PDF = 'ODP_TO_PDF',
  RTF_TO_PDF = 'RTF_TO_PDF',
  EPUB_TO_PDF = 'EPUB_TO_PDF',
  TXT_TO_PDF = 'TXT_TO_PDF',
  MD_TO_PDF = 'MD_TO_PDF',
  // New PDF to Formats
  PDF_TO_CSV = 'PDF_TO_CSV',
  PDF_TO_JSON = 'PDF_TO_JSON',
  PDF_TO_XML = 'PDF_TO_XML',
  PDF_TO_PNG = 'PDF_TO_PNG',
  PDF_TO_TIFF = 'PDF_TO_TIFF',
  PDF_TO_BMP = 'PDF_TO_BMP',
  PDF_TO_GIF = 'PDF_TO_GIF',
  PDF_TO_SVG = 'PDF_TO_SVG',
  PDF_TO_EPUB = 'PDF_TO_EPUB',
  PDF_TO_RTF = 'PDF_TO_RTF',
  PDF_TO_HTML = 'PDF_TO_HTML',
  PDF_TO_TEXT = 'PDF_TO_TEXT',
  PDF_TO_MD = 'PDF_TO_MD',
  PDF_TO_ODT = 'PDF_TO_ODT',
  PDF_TO_TSV = 'PDF_TO_TSV',
  PDF_TO_WEBP = 'PDF_TO_WEBP',
  // New Professional Tools
  HEIC_TO_PDF = 'HEIC_TO_PDF',
  PUB_TO_PDF = 'PUB_TO_PDF',
  WEBP_TO_PDF = 'WEBP_TO_PDF',
  TSV_TO_PDF = 'TSV_TO_PDF',
  // 10 New Converters
  PDF_TO_JPG_ZIP = 'PDF_TO_JPG_ZIP',
  PDF_TO_PNG_ZIP = 'PDF_TO_PNG_ZIP',
  JFIF_TO_PDF = 'JFIF_TO_PDF',
  PDF_TO_JFIF = 'PDF_TO_JFIF',
  ICO_TO_PDF = 'ICO_TO_PDF',
  PDF_TO_ICO = 'PDF_TO_ICO',
  RAW_TO_PDF = 'RAW_TO_PDF',
  PDF_TO_RAW = 'PDF_TO_RAW',
  XPS_TO_PDF = 'XPS_TO_PDF',
  PDF_TO_XPS = 'PDF_TO_XPS',


  PRICING = 'PRICING',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  LOGIN = 'LOGIN',
  QR_GENERATOR = 'QR_GENERATOR',
  API_PORTAL = 'API_PORTAL',
  COMING_SOON = 'COMING_SOON', // New Placeholder
  TEAMS = 'TEAMS',
  ABOUT = 'ABOUT', // New About
  DOCUMENTATION = 'DOCUMENTATION',
  BLOG = 'BLOG',
  ROADMAP = 'ROADMAP',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  PROFILE = 'PROFILE'
}

export interface Tool {
  id: string;
  title: string;
  description: string;
  icon: any;
  view: AppView;
  isNew?: boolean;
  isAi?: boolean;
  category?: 'Organize' | 'Convert To PDF' | 'Convert From PDF' | 'Edit' | 'Security' | 'AI' | 'Other';
}
